spring.threads.virtual.enabled=true
vci.issuer-url=https://localhost:8443

spring.ssl.bundle.jks.server.keystore.location=classpath:localhost.p12
spring.ssl.bundle.jks.server.keystore.password=changeit
spring.ssl.bundle.jks.server.keystore.type=PKCS12
server.ssl.bundle=server
server.port=8443

logging.level.org.springframework.web.servlet.DispatcherServlet=TRACE
