spring.threads.virtual.enabled=true
vci.issuer-url=https://localhost:8443
oid4vp.verifier-url=https://localhost:8443
oid4vp.client-id=localhost
oid4vp.signing-keystore.location=classpath:oid4vp-verifier.p12
oid4vp.signing-keystore.password=changeit
oid4vp.signing-keystore.alias=oid4vp-verifier
vci.signing-keystore.location=classpath:issuer.p12
vci.signing-keystore.password=changeit
vci.signing-keystore.alias=issuer

spring.ssl.bundle.jks.server.keystore.location=classpath:localhost.p12
spring.ssl.bundle.jks.server.keystore.password=changeit
spring.ssl.bundle.jks.server.keystore.type=PKCS12
server.ssl.bundle=server
server.port=8443

logging.level.org.springframework.web.servlet.DispatcherServlet=TRACE
