services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8443:8443"
    env_file:
      - .env
    environment:
      VCI_SIGNING_KEYSTORE_LOCATION: file:/certs/issuer.p12
      VCI_SIGNING_KEYSTORE_PASSWORD: changeit
      VCI_SIGNING_KEYSTORE_ALIAS: issuer
      OID4VP_SIGNING_KEYSTORE_LOCATION: file:/certs/oid4vp-verifier.p12
      OID4VP_SIGNING_KEYSTORE_PASSWORD: changeit
      OID4VP_SIGNING_KEYSTORE_ALIAS: oid4vp-verifier
      SPRING_SSL_BUNDLE_JKS_SERVER_KEYSTORE_LOCATION: file:/certs/server.p12
      SPRING_SSL_BUNDLE_JKS_SERVER_KEYSTORE_PASSWORD: changeit
    volumes:
      - ./certs:/certs:ro
